from __future__ import annotations

from pathlib import Path

from lunaice.labeling.data_models import LABEL_NAMES
from lunaice.labeling.validation.validator import LabelRegionMetrics


class LabelQualityReport:
    def __init__(self, output_dir: Path):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate(self, region_metrics: list[LabelRegionMetrics],
                 global_stats: dict) -> Path:
        rows = []
        for m in region_metrics:
            distr_str = "; ".join(f"{k}: {v}" for k, v in m.label_distribution.items())
            rows.append(f"""
            <tr>
                <td>{m.name}</td>
                <td>{m.n_pixels}</td>
                <td>{m.mean_confidence:.3f}</td>
                <td>{m.mean_disagreement:.3f}</td>
                <td>{m.high_conf_fraction:.3f}</td>
                <td>{m.ice_favorable_fraction:.3f}</td>
                <td>{distr_str}</td>
            </tr>""")

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>POLARIS Label Quality Report</title>
<style>
body {{ font-family: 'Segoe UI', sans-serif; margin: 2em; background: #f5f5f5; }}
.container {{ max-width: 1200px; margin: auto; background: white; padding: 2em; border-radius: 8px; }}
h1 {{ color: #1a1a2e; }}
table {{ border-collapse: collapse; width: 100%; margin: 1em 0; }}
th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
th {{ background: #1a1a2e; color: white; }}
tr:nth-child(even) {{ background: #f9f9f9; }}
.summary {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 1em; margin: 1em 0; }}
.card {{ background: #e8f4f8; padding: 1em; border-radius: 8px; text-align: center; }}
.card h3 {{ margin: 0; color: #1a1a2e; }}
.card p {{ font-size: 1.5em; font-weight: bold; margin: 0.5em 0; }}
.footer {{ margin-top: 2em; color: #666; font-size: 0.9em; }}
</style>
</head>
<body>
<div class="container">
<h1>POLARIS Label Quality Report</h1>
<p>Generated by LUNAICE v0.1.0 Phase 4 - Weak Supervision Labeling Framework</p>

<div class="summary">
    <div class="card"><h3>Total Labeled Pixels</h3><p>{global_stats.get('total_pixels', 0):,}</p></div>
    <div class="card"><h3>Ice Favorable %</h3><p>{global_stats.get('ice_favorable_pct', 0):.1f}%</p></div>
    <div class="card"><h3>High Confidence %</h3><p>{global_stats.get('high_confidence_pct', 0):.1f}%</p></div>
    <div class="card"><h3>Label Sources</h3><p>{global_stats.get('n_sources', 0)}</p></div>
    <div class="card"><h3>Disagreement Rate</h3><p>{global_stats.get('disagreement_rate', 0):.3f}</p></div>
    <div class="card"><h3>Fusion Method</h3><p>{global_stats.get('fusion_method', 'N/A')}</p></div>
</div>

<h2>Label Distribution</h2>
<table>
<tr><th>Label</th><th>Count</th><th>Percentage</th></tr>
"""
        for label_name, count in global_stats.get('label_distribution', {}).items():
            pct = global_stats.get('label_pcts', {}).get(label_name, 0)
            html += f"<tr><td>{label_name}</td><td>{count:,}</td><td>{pct:.1f}%</td></tr>\n"

        html += """</table>

<h2>Region-Level Validation</h2>
<table>
<tr>
    <th>Region</th>
    <th>Pixels</th>
    <th>Mean Conf</th>
    <th>Mean Disagreement</th>
    <th>High Conf %</th>
    <th>Ice Fav %</th>
    <th>Label Dist</th>
</tr>
"""
        html += "\n".join(rows)

        html += """
</table>

<h2>Known Candidate Regions</h2>
<p>Validation performed against published lunar ice candidate craters:</p>
<ul>
"""
        for r in region_metrics:
            html += f"<li><strong>{r.name}</strong>: {r.n_pixels} pixels, {r.ice_favorable_fraction*100:.1f}% ice-favorable</li>\n"

        html += """
</ul>

<h2>Scoring Rules Applied</h2>
<ul>
    <li><strong>CPR &gt; 1.2</strong> → High Confidence Ice</li>
    <li><strong>DOP &lt; 0.2</strong> → High Confidence Ice (low depolarization)</li>
    <li><strong>Inside PSR</strong> → Likely Ice</li>
    <li><strong>L+S CPR &gt; 1</strong> → High Confidence (multi-frequency agreement)</li>
    <li><strong>Volume+Dihedral scattering</strong> → High Confidence Ice</li>
    <li><strong>Slope &lt; 2 deg</strong> → Likely Ice</li>
    <li><strong>Illumination &lt; 1%</strong> → Likely Ice</li>
    <li><strong>Published candidate region</strong> → High Confidence Ice</li>
</ul>

<div class="footer">
    <p>POLARIS - Polar Ice Resource Analysis System</p>
    <p>LUNAICE v0.1.0 | Chandrayaan-2 DFSAR | South Pole Lunar Ice Detection</p>
</div>
</div>
</body>
</html>"""

        out_path = self.output_dir / "label_quality_report.html"
        out_path.write_text(html)
        return out_path
